### PR TITLE
Migrate legacy assignment syntax in {% with %}

### PR DESCRIPTION
**Pull request by adamchainz**
For #82.

### CODE REVIEW

**Comment by GitRon** [comment]
Hi @adamchainz 

just realised that this fixer doesn't seem to have any effect. All `{% with x as y %}` stay as they are. Am I missing something?

What I did:
* Checked that the template is being found (added a `trans` tag which got fixed).
* Updated to v1.2.0
* Tried it in two different projects

Here's my config:

```yml
  - repo: https://github.com/adamchainz/djade-pre-commit
    rev: 1.2.0
    hooks:
    -   id: djade
        args: [--target-version, "5.1"]
        exclude: |
          (?x)^(
            charts/.*
            |.*\.py
          )$
```

Thx and best regards
Ronny

**Comment by adamchainz** [comment]
It's not released.

**Comment by GitRon** [comment]
Omg... I feel tremendously stupid. 🙈 Saw it in the readme and didn't check when it was introduced. Sorry about that...

**Comment by adamchainz** [comment]
No worries, happens to us all!

**Comment by adamchainz** [comment]
It's out now, in 1.3.0, released earlier today.

**Pull request merged**
